#yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Lint TypeScript
      run: npm run lint
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      id: hadolint
      with:
        dockerfile: Dockerfile
    - run: |
        echo "### Hadolint - ${{ steps.hadolint.outcome}}" >> $GITHUB_STEP_SUMMARY
        echo "${process.env.HADOLINT_RESULTS}" >> $GITHUB_STEP_SUMMARY
    - uses: ArtiomTr/jest-coverage-report-action@v2
